//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillBotv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class channel
    {
        public decimal Id { get; set; }
        public decimal ServerId { get; set; }
    
        public virtual server server { get; set; }
    }
}
